### PR TITLE
Ensure quiz file attachments are queued correctly

### PR DESCRIPTION
**Pull request by dwinn**
Ensure quiz file attachments are queued correctly

### CODE REVIEW

**Review by matdelong — APPROVED** [review]
It seems fine, but a bit out of my depht.

**Review by jmcgettrick — APPROVED** [review]
Looks good, you'll be a quiz maintainer for Moodle after all this!

**Comment by dwinn** [comment]
Requesting new code reviews due to significant changes since the two approvals.

**Review by matdelong — APPROVED** [review]

**Review by grijeshsaini — APPROVED** [review]

**Review by jmcgettrick — APPROVED** [review]

**Comment by dwinn** [comment]
Apologise @matdelong, was meant to re-request a review on #72 not this one.

**Comment by dwinn** [comment]
Merging this as it has passed our QA.

**Pull request merged**
